// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM8-0vljiN8xnafqOikoheN3qOvXzzzQM',
    appId: '1:997630717154:web:9e06e281747e64621902bb',
    messagingSenderId: '997630717154',
    projectId: 'madeb75-76019',
    authDomain: 'madeb75-76019.firebaseapp.com',
    storageBucket: 'madeb75-76019.firebasestorage.app',
    measurementId: 'G-F759SD76LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArznB5obpPNEjT6LV-1WAu92LsP7c2XVk',
    appId: '1:997630717154:android:b5026038ef8b12661902bb',
    messagingSenderId: '997630717154',
    projectId: 'madeb75-76019',
    storageBucket: 'madeb75-76019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXl5G_e7XFEldQlOaPR6OJh7FVcARFsU0',
    appId: '1:997630717154:ios:1ec8d4a3706ad1ea1902bb',
    messagingSenderId: '997630717154',
    projectId: 'madeb75-76019',
    storageBucket: 'madeb75-76019.firebasestorage.app',
    iosBundleId: 'com.madeb75.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXl5G_e7XFEldQlOaPR6OJh7FVcARFsU0',
    appId: '1:997630717154:ios:1ec8d4a3706ad1ea1902bb',
    messagingSenderId: '997630717154',
    projectId: 'madeb75-76019',
    storageBucket: 'madeb75-76019.firebasestorage.app',
    iosBundleId: 'com.madeb75.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM8-0vljiN8xnafqOikoheN3qOvXzzzQM',
    appId: '1:997630717154:web:592add2866b1db921902bb',
    messagingSenderId: '997630717154',
    projectId: 'madeb75-76019',
    authDomain: 'madeb75-76019.firebaseapp.com',
    storageBucket: 'madeb75-76019.firebasestorage.app',
    measurementId: 'G-76W23K393T',
  );

}